
services:
  app-rango:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db-rango:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-rango:3306/rango_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: on-failure

  db-rango:
    image: mysql:8.4
    container_name: db-rango-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
        - MYSQL_DATABASE=rango_db
        - MYSQL_ROOT_PASSWORD=12345
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p12345"]
      interval: 10s
      timeout: 5s
      retries: 5



volumes:
  mysql-data:
